# For more information: https://laravel.com/docs/sail
version: "3.7"
services:
  app:
    build:
      args:
        user: devsam
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: spbiacdocker
    container_name: spbiacdocker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - spbiacdocker

  mysql:
    image: mysql:5.7
    container_name: spbiacdocker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - spbiacdocker

  nginx:
    image: nginx:1.17-alpine
    container_name: spbiacdocker-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - spbiacdocker


networks:
  spbiacdocker:
    driver: bridge
